// flow-typed signature: a1a424b2880805af3b08d708edd3e659
// flow-typed version: <<STUB>>/react-sketchapp_v1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sketchapp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sketchapp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sketchapp/__tests__/components/Artboard' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/Document' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/Image' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/Page' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/RedBox' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/Svg' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/Text' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/components/View' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/computeTextTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/computeYogaNode' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/computeYogaTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/hacksForJSONImpl' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/layerGroup' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/models' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/shapeLayers' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/style' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/jsonUtils/textLayers' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/sharedStyles/TextStyles' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/utils/compose' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/utils/sortObjectKeys' {
  declare module.exports: any;
}

declare module 'react-sketchapp/__tests__/utils/zIndex' {
  declare module.exports: any;
}

declare module 'react-sketchapp/flow-typed/fbjs' {
  declare module.exports: any;
}

declare module 'react-sketchapp/flow-typed/sketch' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/buildTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Artboard' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Document' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Image' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Page' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/RedBox' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/ResizingConstraintPropTypes' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Circle' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/ClipPath' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Defs' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Ellipse' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/G' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Image' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Line' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/LinearGradient' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Path' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Pattern' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Polygon' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Polyline' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/props' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/RadialGradient' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Rect' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Stop' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Svg' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Symbol' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Text' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/TextPath' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/TSpan' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Svg/Use' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/Text' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/View' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/components/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/debug' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/flexToSketchJSON' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/computeTextTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/computeYogaNode' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/computeYogaTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/hacksForJSONImpl' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/layerGroup' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/models' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/shapeLayers' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/style' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/jsonUtils/textLayers' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/Platform' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/render' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/ArtboardRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/ImageRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/SketchRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/SvgRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/SymbolInstanceRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/SymbolMasterRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/TextRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/renderers/ViewRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/resets' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/sharedStyles/TextStyles' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/stylesheet/expandStyle' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/stylesheet/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/symbol' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/types' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/compose' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/constants' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/Context' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/createStringMeasurer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/findFont' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/hasAnyDefined' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/hashStyle' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/pick' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/same' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/sortObjectKeys' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/utils/zIndex' {
  declare module.exports: any;
}

declare module 'react-sketchapp/lib/wrappers/sharedTextStyles' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/buildTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Artboard' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Document' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Image' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Page' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/RedBox' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/ResizingConstraintPropTypes' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Circle' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/ClipPath' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Defs' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Ellipse' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/G' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Image' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Line' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/LinearGradient' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Path' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Pattern' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Polygon' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Polyline' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/props' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/RadialGradient' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Rect' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Stop' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Svg' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Symbol' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Text' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/TextPath' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/TSpan' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Svg/Use' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/Text' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/View' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/components/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/debug' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/flexToSketchJSON' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/computeTextTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/computeYogaNode' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/computeYogaTree' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/hacksForJSONImpl' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/layerGroup' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/models' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/shapeLayers' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/style' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/jsonUtils/textLayers' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/Platform' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/render' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/ArtboardRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/ImageRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/SketchRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/SvgRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/SymbolInstanceRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/SymbolMasterRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/TextRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/renderers/ViewRenderer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/resets' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/sharedStyles/TextStyles' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/stylesheet/expandStyle' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/stylesheet/index' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/symbol' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/types' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/compose' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/constants' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/Context' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/createStringMeasurer' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/findFont' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/hasAnyDefined' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/hashStyle' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/isNullOrUndefined' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/pick' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/same' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/sortObjectKeys' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/utils/zIndex' {
  declare module.exports: any;
}

declare module 'react-sketchapp/src/wrappers/sharedTextStyles' {
  declare module.exports: any;
}

declare module 'react-sketchapp/template/src/my-command' {
  declare module.exports: any;
}

declare module 'react-sketchapp/yogafix' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sketchapp/__tests__/components/Artboard.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/Artboard'>;
}
declare module 'react-sketchapp/__tests__/components/Document.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/Document'>;
}
declare module 'react-sketchapp/__tests__/components/Image.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/Image'>;
}
declare module 'react-sketchapp/__tests__/components/Page.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/Page'>;
}
declare module 'react-sketchapp/__tests__/components/RedBox.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/RedBox'>;
}
declare module 'react-sketchapp/__tests__/components/Svg.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/Svg'>;
}
declare module 'react-sketchapp/__tests__/components/Text.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/Text'>;
}
declare module 'react-sketchapp/__tests__/components/View.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/components/View'>;
}
declare module 'react-sketchapp/__tests__/index.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/index'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/computeTextTree.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/computeTextTree'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/computeYogaNode.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/computeYogaNode'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/computeYogaTree.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/computeYogaTree'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/hacksForJSONImpl.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/hacksForJSONImpl'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/layerGroup.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/layerGroup'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/models.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/models'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/shapeLayers.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/shapeLayers'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/style.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/style'>;
}
declare module 'react-sketchapp/__tests__/jsonUtils/textLayers.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/jsonUtils/textLayers'>;
}
declare module 'react-sketchapp/__tests__/sharedStyles/TextStyles.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/sharedStyles/TextStyles'>;
}
declare module 'react-sketchapp/__tests__/utils/compose.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/utils/compose'>;
}
declare module 'react-sketchapp/__tests__/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/utils/isNullOrUndefined'>;
}
declare module 'react-sketchapp/__tests__/utils/sortObjectKeys.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/utils/sortObjectKeys'>;
}
declare module 'react-sketchapp/__tests__/utils/zIndex.js' {
  declare module.exports: $Exports<'react-sketchapp/__tests__/utils/zIndex'>;
}
declare module 'react-sketchapp/flow-typed/fbjs.js' {
  declare module.exports: $Exports<'react-sketchapp/flow-typed/fbjs'>;
}
declare module 'react-sketchapp/flow-typed/sketch.js' {
  declare module.exports: $Exports<'react-sketchapp/flow-typed/sketch'>;
}
declare module 'react-sketchapp/lib/buildTree.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/buildTree'>;
}
declare module 'react-sketchapp/lib/components/Artboard.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Artboard'>;
}
declare module 'react-sketchapp/lib/components/Document.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Document'>;
}
declare module 'react-sketchapp/lib/components/Image.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Image'>;
}
declare module 'react-sketchapp/lib/components/Page.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Page'>;
}
declare module 'react-sketchapp/lib/components/RedBox.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/RedBox'>;
}
declare module 'react-sketchapp/lib/components/ResizingConstraintPropTypes.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/ResizingConstraintPropTypes'>;
}
declare module 'react-sketchapp/lib/components/Svg/Circle.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Circle'>;
}
declare module 'react-sketchapp/lib/components/Svg/ClipPath.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/ClipPath'>;
}
declare module 'react-sketchapp/lib/components/Svg/Defs.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Defs'>;
}
declare module 'react-sketchapp/lib/components/Svg/Ellipse.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Ellipse'>;
}
declare module 'react-sketchapp/lib/components/Svg/G.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/G'>;
}
declare module 'react-sketchapp/lib/components/Svg/Image.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Image'>;
}
declare module 'react-sketchapp/lib/components/Svg/index.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/index'>;
}
declare module 'react-sketchapp/lib/components/Svg/Line.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Line'>;
}
declare module 'react-sketchapp/lib/components/Svg/LinearGradient.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/LinearGradient'>;
}
declare module 'react-sketchapp/lib/components/Svg/Path.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Path'>;
}
declare module 'react-sketchapp/lib/components/Svg/Pattern.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Pattern'>;
}
declare module 'react-sketchapp/lib/components/Svg/Polygon.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Polygon'>;
}
declare module 'react-sketchapp/lib/components/Svg/Polyline.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Polyline'>;
}
declare module 'react-sketchapp/lib/components/Svg/props.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/props'>;
}
declare module 'react-sketchapp/lib/components/Svg/RadialGradient.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/RadialGradient'>;
}
declare module 'react-sketchapp/lib/components/Svg/Rect.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Rect'>;
}
declare module 'react-sketchapp/lib/components/Svg/Stop.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Stop'>;
}
declare module 'react-sketchapp/lib/components/Svg/Svg.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Svg'>;
}
declare module 'react-sketchapp/lib/components/Svg/Symbol.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Symbol'>;
}
declare module 'react-sketchapp/lib/components/Svg/Text.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Text'>;
}
declare module 'react-sketchapp/lib/components/Svg/TextPath.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/TextPath'>;
}
declare module 'react-sketchapp/lib/components/Svg/TSpan.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/TSpan'>;
}
declare module 'react-sketchapp/lib/components/Svg/Use.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Svg/Use'>;
}
declare module 'react-sketchapp/lib/components/Text.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/Text'>;
}
declare module 'react-sketchapp/lib/components/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/TextStylePropTypes'>;
}
declare module 'react-sketchapp/lib/components/View.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/View'>;
}
declare module 'react-sketchapp/lib/components/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/components/ViewStylePropTypes'>;
}
declare module 'react-sketchapp/lib/debug.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/debug'>;
}
declare module 'react-sketchapp/lib/flexToSketchJSON.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/flexToSketchJSON'>;
}
declare module 'react-sketchapp/lib/index.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/index'>;
}
declare module 'react-sketchapp/lib/jsonUtils/computeTextTree.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/computeTextTree'>;
}
declare module 'react-sketchapp/lib/jsonUtils/computeYogaNode.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/computeYogaNode'>;
}
declare module 'react-sketchapp/lib/jsonUtils/computeYogaTree.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/computeYogaTree'>;
}
declare module 'react-sketchapp/lib/jsonUtils/hacksForJSONImpl.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/hacksForJSONImpl'>;
}
declare module 'react-sketchapp/lib/jsonUtils/layerGroup.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/layerGroup'>;
}
declare module 'react-sketchapp/lib/jsonUtils/models.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/models'>;
}
declare module 'react-sketchapp/lib/jsonUtils/shapeLayers.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/shapeLayers'>;
}
declare module 'react-sketchapp/lib/jsonUtils/style.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/style'>;
}
declare module 'react-sketchapp/lib/jsonUtils/textLayers.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/jsonUtils/textLayers'>;
}
declare module 'react-sketchapp/lib/Platform.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/Platform'>;
}
declare module 'react-sketchapp/lib/render.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/render'>;
}
declare module 'react-sketchapp/lib/renderers/ArtboardRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/ArtboardRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/ImageRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/ImageRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/index.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/index'>;
}
declare module 'react-sketchapp/lib/renderers/SketchRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/SketchRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/SvgRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/SvgRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/SymbolInstanceRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/SymbolInstanceRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/SymbolMasterRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/SymbolMasterRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/TextRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/TextRenderer'>;
}
declare module 'react-sketchapp/lib/renderers/ViewRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/renderers/ViewRenderer'>;
}
declare module 'react-sketchapp/lib/resets.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/resets'>;
}
declare module 'react-sketchapp/lib/sharedStyles/TextStyles.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/sharedStyles/TextStyles'>;
}
declare module 'react-sketchapp/lib/stylesheet/expandStyle.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/stylesheet/expandStyle'>;
}
declare module 'react-sketchapp/lib/stylesheet/index.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/stylesheet/index'>;
}
declare module 'react-sketchapp/lib/symbol.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/symbol'>;
}
declare module 'react-sketchapp/lib/types.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/types'>;
}
declare module 'react-sketchapp/lib/utils/compose.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/compose'>;
}
declare module 'react-sketchapp/lib/utils/constants.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/constants'>;
}
declare module 'react-sketchapp/lib/utils/Context.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/Context'>;
}
declare module 'react-sketchapp/lib/utils/createStringMeasurer.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/createStringMeasurer'>;
}
declare module 'react-sketchapp/lib/utils/findFont.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/findFont'>;
}
declare module 'react-sketchapp/lib/utils/hasAnyDefined.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/hasAnyDefined'>;
}
declare module 'react-sketchapp/lib/utils/hashStyle.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/hashStyle'>;
}
declare module 'react-sketchapp/lib/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/isNullOrUndefined'>;
}
declare module 'react-sketchapp/lib/utils/pick.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/pick'>;
}
declare module 'react-sketchapp/lib/utils/same.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/same'>;
}
declare module 'react-sketchapp/lib/utils/sortObjectKeys.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/sortObjectKeys'>;
}
declare module 'react-sketchapp/lib/utils/zIndex.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/utils/zIndex'>;
}
declare module 'react-sketchapp/lib/wrappers/sharedTextStyles.js' {
  declare module.exports: $Exports<'react-sketchapp/lib/wrappers/sharedTextStyles'>;
}
declare module 'react-sketchapp/src/buildTree.js' {
  declare module.exports: $Exports<'react-sketchapp/src/buildTree'>;
}
declare module 'react-sketchapp/src/components/Artboard.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Artboard'>;
}
declare module 'react-sketchapp/src/components/Document.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Document'>;
}
declare module 'react-sketchapp/src/components/Image.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Image'>;
}
declare module 'react-sketchapp/src/components/Page.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Page'>;
}
declare module 'react-sketchapp/src/components/RedBox.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/RedBox'>;
}
declare module 'react-sketchapp/src/components/ResizingConstraintPropTypes.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/ResizingConstraintPropTypes'>;
}
declare module 'react-sketchapp/src/components/Svg/Circle.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Circle'>;
}
declare module 'react-sketchapp/src/components/Svg/ClipPath.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/ClipPath'>;
}
declare module 'react-sketchapp/src/components/Svg/Defs.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Defs'>;
}
declare module 'react-sketchapp/src/components/Svg/Ellipse.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Ellipse'>;
}
declare module 'react-sketchapp/src/components/Svg/G.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/G'>;
}
declare module 'react-sketchapp/src/components/Svg/Image.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Image'>;
}
declare module 'react-sketchapp/src/components/Svg/index.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/index'>;
}
declare module 'react-sketchapp/src/components/Svg/Line.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Line'>;
}
declare module 'react-sketchapp/src/components/Svg/LinearGradient.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/LinearGradient'>;
}
declare module 'react-sketchapp/src/components/Svg/Path.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Path'>;
}
declare module 'react-sketchapp/src/components/Svg/Pattern.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Pattern'>;
}
declare module 'react-sketchapp/src/components/Svg/Polygon.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Polygon'>;
}
declare module 'react-sketchapp/src/components/Svg/Polyline.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Polyline'>;
}
declare module 'react-sketchapp/src/components/Svg/props.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/props'>;
}
declare module 'react-sketchapp/src/components/Svg/RadialGradient.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/RadialGradient'>;
}
declare module 'react-sketchapp/src/components/Svg/Rect.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Rect'>;
}
declare module 'react-sketchapp/src/components/Svg/Stop.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Stop'>;
}
declare module 'react-sketchapp/src/components/Svg/Svg.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Svg'>;
}
declare module 'react-sketchapp/src/components/Svg/Symbol.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Symbol'>;
}
declare module 'react-sketchapp/src/components/Svg/Text.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Text'>;
}
declare module 'react-sketchapp/src/components/Svg/TextPath.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/TextPath'>;
}
declare module 'react-sketchapp/src/components/Svg/TSpan.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/TSpan'>;
}
declare module 'react-sketchapp/src/components/Svg/Use.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Svg/Use'>;
}
declare module 'react-sketchapp/src/components/Text.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/Text'>;
}
declare module 'react-sketchapp/src/components/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/TextStylePropTypes'>;
}
declare module 'react-sketchapp/src/components/View.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/View'>;
}
declare module 'react-sketchapp/src/components/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-sketchapp/src/components/ViewStylePropTypes'>;
}
declare module 'react-sketchapp/src/debug.js' {
  declare module.exports: $Exports<'react-sketchapp/src/debug'>;
}
declare module 'react-sketchapp/src/flexToSketchJSON.js' {
  declare module.exports: $Exports<'react-sketchapp/src/flexToSketchJSON'>;
}
declare module 'react-sketchapp/src/index.js' {
  declare module.exports: $Exports<'react-sketchapp/src/index'>;
}
declare module 'react-sketchapp/src/jsonUtils/computeTextTree.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/computeTextTree'>;
}
declare module 'react-sketchapp/src/jsonUtils/computeYogaNode.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/computeYogaNode'>;
}
declare module 'react-sketchapp/src/jsonUtils/computeYogaTree.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/computeYogaTree'>;
}
declare module 'react-sketchapp/src/jsonUtils/hacksForJSONImpl.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/hacksForJSONImpl'>;
}
declare module 'react-sketchapp/src/jsonUtils/layerGroup.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/layerGroup'>;
}
declare module 'react-sketchapp/src/jsonUtils/models.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/models'>;
}
declare module 'react-sketchapp/src/jsonUtils/shapeLayers.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/shapeLayers'>;
}
declare module 'react-sketchapp/src/jsonUtils/style.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/style'>;
}
declare module 'react-sketchapp/src/jsonUtils/textLayers.js' {
  declare module.exports: $Exports<'react-sketchapp/src/jsonUtils/textLayers'>;
}
declare module 'react-sketchapp/src/Platform.js' {
  declare module.exports: $Exports<'react-sketchapp/src/Platform'>;
}
declare module 'react-sketchapp/src/render.js' {
  declare module.exports: $Exports<'react-sketchapp/src/render'>;
}
declare module 'react-sketchapp/src/renderers/ArtboardRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/ArtboardRenderer'>;
}
declare module 'react-sketchapp/src/renderers/ImageRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/ImageRenderer'>;
}
declare module 'react-sketchapp/src/renderers/index.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/index'>;
}
declare module 'react-sketchapp/src/renderers/SketchRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/SketchRenderer'>;
}
declare module 'react-sketchapp/src/renderers/SvgRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/SvgRenderer'>;
}
declare module 'react-sketchapp/src/renderers/SymbolInstanceRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/SymbolInstanceRenderer'>;
}
declare module 'react-sketchapp/src/renderers/SymbolMasterRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/SymbolMasterRenderer'>;
}
declare module 'react-sketchapp/src/renderers/TextRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/TextRenderer'>;
}
declare module 'react-sketchapp/src/renderers/ViewRenderer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/renderers/ViewRenderer'>;
}
declare module 'react-sketchapp/src/resets.js' {
  declare module.exports: $Exports<'react-sketchapp/src/resets'>;
}
declare module 'react-sketchapp/src/sharedStyles/TextStyles.js' {
  declare module.exports: $Exports<'react-sketchapp/src/sharedStyles/TextStyles'>;
}
declare module 'react-sketchapp/src/stylesheet/expandStyle.js' {
  declare module.exports: $Exports<'react-sketchapp/src/stylesheet/expandStyle'>;
}
declare module 'react-sketchapp/src/stylesheet/index.js' {
  declare module.exports: $Exports<'react-sketchapp/src/stylesheet/index'>;
}
declare module 'react-sketchapp/src/symbol.js' {
  declare module.exports: $Exports<'react-sketchapp/src/symbol'>;
}
declare module 'react-sketchapp/src/types.js' {
  declare module.exports: $Exports<'react-sketchapp/src/types'>;
}
declare module 'react-sketchapp/src/utils/compose.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/compose'>;
}
declare module 'react-sketchapp/src/utils/constants.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/constants'>;
}
declare module 'react-sketchapp/src/utils/Context.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/Context'>;
}
declare module 'react-sketchapp/src/utils/createStringMeasurer.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/createStringMeasurer'>;
}
declare module 'react-sketchapp/src/utils/findFont.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/findFont'>;
}
declare module 'react-sketchapp/src/utils/hasAnyDefined.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/hasAnyDefined'>;
}
declare module 'react-sketchapp/src/utils/hashStyle.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/hashStyle'>;
}
declare module 'react-sketchapp/src/utils/isNullOrUndefined.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/isNullOrUndefined'>;
}
declare module 'react-sketchapp/src/utils/pick.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/pick'>;
}
declare module 'react-sketchapp/src/utils/same.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/same'>;
}
declare module 'react-sketchapp/src/utils/sortObjectKeys.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/sortObjectKeys'>;
}
declare module 'react-sketchapp/src/utils/zIndex.js' {
  declare module.exports: $Exports<'react-sketchapp/src/utils/zIndex'>;
}
declare module 'react-sketchapp/src/wrappers/sharedTextStyles.js' {
  declare module.exports: $Exports<'react-sketchapp/src/wrappers/sharedTextStyles'>;
}
declare module 'react-sketchapp/template/src/my-command.js' {
  declare module.exports: $Exports<'react-sketchapp/template/src/my-command'>;
}
declare module 'react-sketchapp/yogafix.js' {
  declare module.exports: $Exports<'react-sketchapp/yogafix'>;
}
